package com.example.compose

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF875200)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDDBA)
val md_theme_light_onPrimaryContainer = Color(0xFF2B1700)
val md_theme_light_secondary = Color(0xFF715A41)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFDDDBD)
val md_theme_light_onSecondaryContainer = Color(0xFF281805)
val md_theme_light_tertiary = Color(0xFF8F4E00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDCC1)
val md_theme_light_onTertiaryContainer = Color(0xFF2E1500)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1F1B16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1F1B16)
val md_theme_light_surfaceVariant = Color(0xFFF1DFD0)
val md_theme_light_onSurfaceVariant = Color(0xFF50453A)
val md_theme_light_outline = Color(0xFF827568)
val md_theme_light_inverseOnSurface = Color(0xFFFAEFE7)
val md_theme_light_inverseSurface = Color(0xFF352F2A)
val md_theme_light_inversePrimary = Color(0xFFFFB866)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF875200)
val md_theme_light_outlineVariant = Color(0xFFD4C4B5)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB866)
val md_theme_dark_onPrimary = Color(0xFF482900)
val md_theme_dark_primaryContainer = Color(0xFF673D00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDDBA)
val md_theme_dark_secondary = Color(0xFFE0C1A3)
val md_theme_dark_onSecondary = Color(0xFF3F2D17)
val md_theme_dark_secondaryContainer = Color(0xFF58432C)
val md_theme_dark_onSecondaryContainer = Color(0xFFFDDDBD)
val md_theme_dark_tertiary = Color(0xFFFFB779)
val md_theme_dark_onTertiary = Color(0xFF4C2700)
val md_theme_dark_tertiaryContainer = Color(0xFF6C3A00)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDCC1)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1B16)
val md_theme_dark_onBackground = Color(0xFFEBE1D9)
val md_theme_dark_surface = Color(0xFF1F1B16)
val md_theme_dark_onSurface = Color(0xFFEBE1D9)
val md_theme_dark_surfaceVariant = Color(0xFF50453A)
val md_theme_dark_onSurfaceVariant = Color(0xFFD4C4B5)
val md_theme_dark_outline = Color(0xFF9D8E81)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1B16)
val md_theme_dark_inverseSurface = Color(0xFFEBE1D9)
val md_theme_dark_inversePrimary = Color(0xFF875200)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB866)
val md_theme_dark_outlineVariant = Color(0xFF50453A)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFFFA52A)
